### ISSUE TITLE
Clean up compute_Mlincomb(nep::DEP

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#104]
The compute_Mlincomb(::DEP can be cleaned up a bit:

* should be compute_Mlincomb!
* fusing dots
* type logic does not take `a` into account. 
* TODO:doc- tag?
* the if k>1 should not be necessary considering how it is handled in other compute_mlincombs

**Comment by meleg** [comment]
After the fix on the function compute_Mlincomb we get the following improvement for the instance:
```
using NonlinearEigenproblems
using Test
using LinearAlgebra
using IterativeSolvers

nep=nep_gallery("dep0_tridiag",500000)
n=size(nep,1);	k=50;
V=rand(n,k);	λ=rand()*im+rand(); a=rand(k)
z1=compute_Mlincomb!(nep,λ,copy(V),a)
compute_Mlincomb(nep,λ,V,a)
@time z1=compute_Mlincomb!(nep,λ,V,a)
```
On the branch compute_Mlincomb_DEP
`  0.164676 seconds (33 allocations: 41.967 MiB, 32.51% gc time)`
on the master
`  0.211399 seconds (56 allocations: 118.263 MiB, 32.24% gc time)`
