### ISSUE TITLE
Dependency AbstractAlgebra and PolynomialZeros

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#120]
I'm afraid we will have to deactivate or try to get around the use of PolynomialZeros which depends on AbstractAlgebra. The "welcome to" message is not acceptable for us. I don't think they will remove it any time soon considering the responses to my request to remove it on their github (see issue 158 in  https://github.com/Nemocas/AbstractAlgebra.jl). We can look into other polynomial root finder packages.

**Comment by meleg** [comment]
Naive question: can we just use a naive approach like computing the eigenvalues of a (scaled) companion matrix as root-finder? We usually do not have very ill-conditioned polynomial (as far as I know).

**Comment by jarlebring** [comment]
One of the reasons we moved to this particular package was its support for BigFloat. `eigen` doesnt support BigFloat so that naive approach would need some "hacks" to work.

**Comment by maxbennedich** [comment]
We can create a new package called `AbstractAlgebraWithoutTheWelcomeMessage.jl`, which is a copy of theirs but with the welcome message removed. It can be automated to always stay in sync with their repository. Their license seems to allow it. 😛

**Comment by meleg** [comment]
I suggest one of these options:
- We implement our own polynomial root finder (maybe we can simply use the Ehrlich-Aberth method), We should be able to do it in BigFloat.
- We use the eigenvalue of compation matrix (and we do not support BigFloat)
- We try another package

I am slightly more in favor of the first option (and volunteer for eventually trying).

**Comment by jarlebring** [comment]
Approach 2 can be fixed to work for bigfloats. Basically do an eigen implementation for BigFloat matrices: Round to Float64 => use eigen on Float => Use result as starting value for two steps of inverse iteration. 

I would be slightly in favor of approach 2, since the changes seem the smallest and removes a dependency. 

The EA method is not the most common approach for poly roots, and I see a high risk of a hidden amount of work required to design starting values and treat special cases.

**Comment by jarlebring** [comment]
I will close this and maybe revisit it if the abstract algebra package changes behavior.
