### ISSUE TITLE
Only base-type InnerSolver exported

### ISSUE THREAD

**Issue by eringh** [nep-pack/NonlinearEigenproblems.jl#130]
I looked at `inner_solver.jl` and noticed that only the base-type `InnerSolver` is exported, and not the specific ones. Should we export the specific ones as well, or does that contaminate namespace too much?
As it is now you always have to write `NEPSolver.DefaultInnerSolver` etc.

**Comment by jarlebring** [comment]
They are typical user types, so I think they should be exported.
