### ISSUE TITLE
SPMF_NEP_dense and SPMF_NEP_sparse

### ISSUE THREAD

**Issue by eringh** [nep-pack/NonlinearEigenproblems.jl#131]
In `NEPTypes.jl` i found some scattered code regarding `SPMF_NEP_dense` and `SPMF_NEP_sparse`. Should these be there or did we remove them? What is the status?

**Comment by jarlebring** [comment]
SPMF_NEP_sparse should be an alias. I SPMF_NEP_dense is not defined so it should not be there.

**Comment by eringh** [comment]
Ok. Then I'll remove the `SPMF_NEP_dense`.
