### ISSUE TITLE
Should we keep the function nlevp_make_native

### ISSUE THREAD

**Issue by eringh** [nep-pack/NonlinearEigenproblems.jl#135]
NEP-PACK has two major way of working with the NLEVP collection. One is via the MATLAB interface. The other is via native implementations. However, the latter can be accessed in two different ways, with different implementations. We have the native implementations in `nep_gallery()`, and then we have the ones that are accessible via the MATLAB-interface and `nlevp_make_native()`.

Both  `nep_gallery()` and `nlevp_make_native()` constructs native NEP-PACK objects. Is there a relation? Is there a need for both?

**Comment by jarlebring** [comment]
If someone would convert "cd_player" to native, there is no loss of functionality by removing nlevp_make_native. It's a PEP, so not so difficult.

**Comment by eringh** [comment]
I can try to do it!

**Comment by jarlebring** [comment]
Good. I recommend converting the matrices using the serialization code for sparse matrices max wrote: `utils/Serialization.jl`
