### ISSUE TITLE
plotting

### ISSUE THREAD

**Issue by meleg** [nep-pack/NonlinearEigenproblems.jl#143]
As you know, it is not simple to plot in julia 1.0 since not all the packages are updated. In addition to that, `MAT` fails in the precompilation. See Issue 90 in https://github.com/JuliaIO/MAT.jl

This is my current workaround using matlab:

In julia:
```
x=Vector(0:0.1:pi)
y=sin.(x)
using DelimitedFiles
writedlm("test.txt",[x,y])
```

In matlab
```
M=importdata("test.txt"); % store as matrix
x=M(1,:); y=M(2,:);
plot(x,y)
```
What do you use for plotting? This method is quick and simple but it would be great to plot without opening matlab.

**Comment by maxbennedich** [comment]
Plotting works fine for me now:
```julia
Pkg.add("Plots")
using Plots
plot(1:3,4:6)
```
I also have some [test code checked in here](https://github.com/nep-pack/NonlinearEigenproblems.jl/blob/master/test/nleigs/nleigs_residual_plot.jl) which does plotting and works for me without issues.

How are you doing the plotting in Julia, and how does it fail?

**Comment by jarlebring** [comment]
Last time I checked `using Plots` did not work, but after doing package update `] up`, it seems to work, several backends
```julia
julia> using Plots
julia> Plots.backend() # show current plotting backend 
Plots.GRBackend()
julia> plot(1:3,(1:3).^2)
julia> Plots.backend()
Plots.GRBackend()
julia> plotly();
julia> Plots.backend()
Plots.PlotlyBackend()
julia> plot(1:3,(1:3).^2)
```
I prefer `plotly` due to more functionality.  

However, the backend `pyplot()` which used to be my preferred backend, does not work directly.

**Comment by maxbennedich** [comment]
GR and Plotly both work out of the box for me too, while PyPlot is a bit tricky to get started.

[InspectDR](http://docs.juliaplots.org/latest/examples/inspectdr/) also works for me, but seems inferior to the others.

[UnicodePlots](http://docs.juliaplots.org/latest/examples/unicodeplots/) also works, for plotting in the terminal.

I was also able to get Gadfly up and running following [these instructions](https://discourse.julialang.org/t/which-plot-packages-works-perfectly-on-julia-1-0-0/15440/16). Unlike the others, it is not based on `Plots`.

**Comment by meleg** [comment]
After a  package update (and other small fixes) it works. Thanks for the help.
