### ISSUE TITLE
nlar test fails

### ISSUE THREAD

**Issue by meleg** [nep-pack/NonlinearEigenproblems.jl#151]
The nlar test is currently failing (at least on my computer). 
I have recently worked on a branch but I did not touch that function directly or indirectly (I hope). However I cannot figure it out what can be the problem. Now the test is brute-force commented.

 I will try to fix it, can I get some help (@upadpup?)

**Comment by meleg** [comment]
It was because I changed something in IAR. I fixed it now. Soon I will push the fix.

**Comment by jarlebring** [comment]
:+1:
