### ISSUE TITLE
Removing compute_eigvec_from_eigval 

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#154]
In NEPSolver.jl we currently have two functions `compute_eigvec_from_eigval_lu` and `compute_eigvec_from_eigval_lopcg`. They originate from a situation when the user specified a shift which was too close to an eigenvalue. 

These functions / functionality is incomplete in many ways, and I think the problem they solve is not so important (since a user can anyway select a different shift). I suggest we remove these and replace the calls in the NEPSolvers with generating an error. The best code is no code at all https://blog.codinghorror.com/the-best-code-is-no-code-at-all/

**Comment by eringh** [comment]
After the removal from Beyn contour method it seems as if these functions are used in:
- `newton`
- `augnewton`
- `quasinewton`
- `newtonqr`
- `implicitdet`
- `resinv`
- `rfi`
- `rfi_b`

Is it always a shift too close to the eigenvalue that causes the singular case, can it not also be that the current iterate it too close to an eigenvalue but we have not yet computed a good enough approximation to the eigenvector? In that case, should we throw an error, or just a warning, or perhaps let the user specify?

**Comment by jarlebring** [comment]
The problem that we aimed to solve was that if the shift was already an eigval, then we received an error. We preferred that the method returns an eigpair. In the interest of reducing the code-base I think this should be reconsidered. Letting the user provide what happens seems like [feature creeping](https://en.wikipedia.org/wiki/Feature_creep), and would generate more code.

The current solution captures some cases but not all.  Sometimes LAPACK throws an `LAPACKUnknwonError` if the matrix is singular and we only capture `SingularException`. So the current solution is hackish, does not cover all cases, and contains quite a bit of code.

I would say just let the error propagate all the way to the user.
