### ISSUE TITLE
Convenience functions/types for reduced compute functions types

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#159]
As you can see in the tutorials https://nep-pack.github.io/NonlinearEigenproblems.jl/tutorial_matlab1/ and https://nep-pack.github.io/NonlinearEigenproblems.jl/tutorial_call_python/ one currently has to define new NEP-types if one has an external compute_Mder function (or compute_Mlincomb). This seems a bit complicated considering how common it is. 

We could add a `compute_Mder_NEP` which takes a function as input, such that the MATLAB tutorial example would be:
```
julia> nep=compute_Mder_NEP((s,v) -> mat"compute_derivative_k(double($s),double($der))",10)
```
It would then default to using `compute_Mlincomb_from_Mder`, maybe also something similar for `compute_MM`.

**Comment by eringh** [comment]
The thought crossed my mind when I saw the tutorials (Matlab and Python). However, I have not had time to think it through properly. Perhaps some structure is more favorable than some other.
But in general I think it sounds very nice!
