### ISSUE TITLE
Unknown nof eigvals-mode for arnoldi methods

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#177]
Currently, iar, tiar, nlarnoldi, etc take the number of wanted eigenvalues as input: 
```
iar(nep,Neig=3)
```
If `Neig` eigenvalues are not found, an error is thrown. When working on a specific application, I realize the fact that I don't know how many eigenvalues I want beforehand. Instead, I would like it to run  `maxit` iterations and just return as many eigenvalues as have converged at that point.

Feature request: We let this be the behavior if `Neig=Inf`. The only difference would (essentially) be that we do not throw an error after `maxit` iterations, but we just return the currently computed solutions. 

This seems to already (partially?) implemented if we look at the end of `iar`. It is however not activated in tiar. 

It should also be documented in `?iar` etc

**Comment by eringh** [comment]
Should this be done also for _infinite Lanczos_ och _infinite bi-Lanczos_? In such case, should we consider doing some kind of code-reuse functionality? Right now there is almost the same code in a few places (the bug in #178 has been so far been corrected in three different methods).

**Comment by eringh** [comment]
_Infinite Lanczos_ (`ilan`) could possibly also get this behavior. Is that desired, @meleg?

**Comment by jarlebring** [comment]
Minor. I think you can just fix it, without disturbing the parental leave.

**Comment by eringh** [comment]
Are there any other methods we should consider having this behavior in? I am not sure if `nlar` or `jd ` are suitable for it. It could possibly be done, but with a penalty in the pre-allocated memory.
