### ISSUE TITLE
Aligning notation Neig or neigs

### ISSUE THREAD

**Issue by eringh** [nep-pack/NonlinearEigenproblems.jl#184]
I found that we use different notation for the number of desired eigenvalues in different part of the code. We use `Neig` in the infinite Arnoldi-type methods, jd, and the inner-solver interface. However, we use `neigs` in nonlinear Arnoldi and Beyn controur. Should I align the notation or are there reasons for having it different?

**Comment by jarlebring** [comment]
https://github.com/nep-pack/NonlinearEigenproblems.jl/wiki/Style-guidelines-and-notes
