### ISSUE TITLE
Bug in DefaultLinSolver creator

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#196]
According to the git-history @meleg modified this code in LinSolver in 24c3a70eb795275133d4956f26e18573c1b6a1f0.

```julia
function DefaultLinSolver(nep::NEP, λ, umfpack_refinements)
        A=compute_Mder(nep,λ)
        if isposdef(A)
            Afact=factorize(A)
        else
            Afact=lu(A)
        end
        Afact=lu(A)
        return DefaultLinSolver(Afact, umfpack_refinements)
end
```

Apparently the matrix is always factorized twice. Probably the last `lu(A)` was a mistake. CPU-timings since that commit have been "wrong" to our favor. Additionally: I don't understand why the if for the `isposdef` is needed. Shouldn't `factorize` handle that by itself?

**Comment by meleg** [comment]
Apparently there is a bug in the function `factorize`.  This function does not work if the input is an indefinite symmetric matrix. The following is a minimal example with a matrix with one eigenvalue positive and one negative,

```
using SparseArrays
using LinearAlgebra
A=sparse([-1 2 ; 2 -1])
factorize(A)
```

the function `lu` works properly. I would just remove the last line of the code that @jarlebring quoted, i.e., re-factorizing with `lu`.

**Comment by jarlebring** [comment]
The problem seems to be present also on Version 1.2.0-rc2.0. Could you see if this is documented in github julia LinearAlgebra? It should be an issue. It would be nice to have a reference to that issue in the code. If you don't find it, try julia discourse.

**Comment by jarlebring** [comment]
Another thing: The function `isposdef` carries out substantial computation. It tries to compute a cholesky factorization. See `?isposdef`. I think this is not something we want to do every time we need to factorize. A different workaround is to add a kwarg `use_lu=false` so you can set it to true in your simulations where it is important.  Note: I default should be set to false.

**Comment by meleg** [comment]
I did not find any issue about this in github julia LinearAlgebra. It may be a special case of another issue, but I did not find it. We can replace `isposdef` with `issymmetric`, it should be faster.

**Comment by meleg** [comment]
Another solution is to `try` to use factorize, if it fails use `ldlt` instead. The following is how to solve the minimal example.
```julia
using SparseArrays
using LinearAlgebra
A=sparse([-1 2 ; 2 -1])

A=try factorize(A)
	catch e
		if isa(e,MethodError)
			ldlt(A)
		end
	end
```
And this is how this fix goes in our code 

```julia
function DefaultLinSolver(nep::NEP, λ, umfpack_refinements)
        A=compute_Mder(nep,λ)
        Afact=try factorize(A)
				catch e
					if isa(e,MethodError)
						ldlt(A)
					end
				end
        return DefaultLinSolver(Afact, umfpack_refinements)
end
```
Can I change the code in this way and close the issue?

**Comment by meleg** [comment]
Apparently the problem arises when the matrix has integer elements. For example, the following works
```julia
using SparseArrays
using LinearAlgebra
A=sparse([-1.0 2 ; 2 -1])
factorize(A)
```
We never have integer matrices, so I would say that this is not a problem for us. I will restore the original code and close the issue.
