### ISSUE TITLE
Releasing your benchmarking utilities (`@bench` macro, etc.) under the MIT license?

### ISSUE THREAD

**Issue by DilumAluthge** [nep-pack/NonlinearEigenproblems.jl#209]
I like the approach that you use in this package for benchmarking your unit tests (the `@bench` macro, the benchmark reports, etc.). I think it could be really useful for other Julia packages to use a similar approach.

Would you be willing to make a new repository containing just the benchmarking utilities under the MIT license? This would allow the authors of other Julia packages to use your benchmarking tools without needing to GPL their code.

**Comment by jarlebring** [comment]
I'm positive. In fact, I would have preferred MIT license for the whole package, but we prioritized the inclusion of a couple of files from a GPL-software (NLEVP benchmark collection). If we get a user-base interested in a MIT-license we might change it later. I just had contact with @maxbennedich who wrote the benchmark-code and he also sounded positive to putting it in a separate repo.

**Comment by maxbennedich** [comment]
Hi Dilum, I've created a new repository with just the benchmarking utilities (and a trivial test application that can be used for testing) under the MIT license here:

https://github.com/maxbennedich/julia-regression-analysis

It's not an independent package, so you'll probably need to adapt it a bit to your project. Let me know if you have any questions.

**Comment by DilumAluthge** [comment]
Awesome, thanks Max!
