### ISSUE TITLE
Doc updates for new gallery example generator

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#220]
The function documentation associated with #218 needs updates. 

These files need new values in the function examples:

* [x] compute_rf_wrapper.jl
* [x] errmeasure.jl
* [x] Gallery.jl
* [x] LinSolvers.jl
* [x] method_beyncontour.jl
* [x] method_blocknewton.jl
* [x] method_broyden.jl
* [x] method_companion.jl
* [x] method_iar_chebyshev.jl
* [x] method_iar.jl
* [x] method_infbilanczos.jl
* [x] method_jd.jl
* [x] method_newton.jl
* [x] method_nlar.jl
* [x] method_nleigs.jl
* [x] method_rfi.jl
* [x] method_rfi.jl
* [x] method_tiar.jl
* [x] NEPCore.jl
* [x] nep_deflation.jl
* [x] NEPTypes.jl
* [x] types_cheb_pep.jl

Also in online documentation

* [x] docs/src/index.md
* [x] docs/src/tutorial_newmethod.md
* [x] docs/src/deflatetutorial.md
* [x] ~~docs/src/deflation.md~~
* [x] docs/src/errmeasure.md
* [x] docs/src/methods.md
* [x] docs/src/innersolvers.md
* [x] docs/src/methods.md
* [x] docs/src/tutorial_linsolve.md

**Comment by eringh** [comment]
Since we are no longer resetting seed in the Gallery we need to be extra careful in the docs and tutorials. We need to specify the starting vectors, otherwise the results are not reproducible.

**Comment by eringh** [comment]
I think that was it. Anything else we might have missed?
