### ISSUE TITLE
Julia 1.2 test - JD failure

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#222]
There seems to be some problems with the jd-test on julia 1.2: 
https://travis-ci.org/nep-pack/NonlinearEigenproblems.jl/jobs/585927072

```
iter 24 err:0.4415028396333377 λ=-14.966577826969802 + 0.0im conveig=2, subspace dim=9

iter 25 err:1.633748107684369 λ=2.6602292544146855 + 0.0im conveig=2, subspace dim=10

iter 26 err:1.941263254990185 λ=0.7336127076095217 + 0.0im conveig=2, subspace dim=11

iter 27 err:5.6371824758170455 λ=-0.9925437756785035 + 0.0im conveig=2, subspace dim=12

iter 28 err:1.4205630478441043 λ=0.3599529906526096 + 0.0im conveig=2, subspace dim=13

Effenberger: Error During Test at /home/travis/build/nep-pack/NonlinearEigenproblems.jl/test/jd.jl:61

  Got exception outside of a @test

  ArgumentError: matrix contains Infs or NaNs

  Stacktrace:

   [1] chkfinite at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/lapack.jl:92 [inlined]

   [2] gebal! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/lapack.jl:204 [inlined]

   [3] exp!(::Array{Complex{Float64},2}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/dense.jl:515

   [4] exp at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/LinearAlgebra/src/dense.jl:479 [inlined]
```

**Comment by eringh** [comment]
I do not manage to recreate the error locally. But I'll take a closer look at it.

**Comment by jarlebring** [comment]
sounds like seed reset related.

**Comment by eringh** [comment]
Sounds like it. The algorithm does a random draw of starting guess for the deflated problem, if the second smallest eigenvalue is not good enough [`(abs(λ-λ2)/abs(λ) > sqrt(eps(real(T)))`)](https://github.com/nep-pack/NonlinearEigenproblems.jl/blob/master/src/method_jd.jl#L399)

**Comment by eringh** [comment]
Seems as if seed reset works https://travis-ci.org/nep-pack/NonlinearEigenproblems.jl/jobs/585951909. I'll wait until the full test has completed before closing this.

**Comment by jarlebring** [comment]
Could also test it locally on 1.0? I haven't figured out how to do the tests for both 1.0 and 1.2 yet...
