### ISSUE TITLE
NEPSolver.nlar() not receiving λ0 parameter

### ISSUE THREAD

**Issue by carlomontec** [nep-pack/NonlinearEigenproblems.jl#241]
Seems NEPSolver.nlar() is not receiving the parameter λ0.  From the source code seems it should be called  λ?

**Comment by jarlebring** [comment]
Thanks. It should follow the same naming as other solvers as we describe in the 
[solver developer style guidelines](https://github.com/nep-pack/NonlinearEigenproblems.jl/wiki/Style-guidelines-and-notes).

**Comment by eringh** [comment]
Solved by #243.
