### ISSUE TITLE
First publicly announced version 

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#26]
This issue is checklist/wishlist of things we should plan to do before we feel we can start announcing the existance of the packade to colleagues (maybe version 0.1). Feel free to add if you think it should be included.
- NLArnoldi
  - [x] Modernization of orthogonalization 
  - [x] Stay real when problem is real
  - [x] One version of restarting
  - [x] Proper function comments
  - [x] Unit testing
  - [x] Throw `NoConvergenceException` if it does not find the specified number of eigenvalues 
  - [x] Selection around disk 
- IAR etc
    *  ~~One version of restart~~
  - [x] Chebyshev version (as different function maybe) 
  - [x] Extraction by projection (instead of Hessenberg)  
  - [x] Proper function comments
  - [x] Proper function comments infbilanczos
- TIAR
  - [x] Extraction by projection
  - [x] Modernize orthogonalization 
  - [x] Proper function comments
- SG 
  - [x] Reimplementation of such that we can compute kth eigenvalue (for minmax problems)
  - [x] Proper function comments
- JD 
  - [x] Reimplementation with new ProjectedNEP 
  - [x] Reimplementation with modern orthogonalization 
  - [x] Reimplement the linear solve to get rid of explicit matrix access (computed via Mlincomb)
  - [x] Implement so that it can be used to compute more than one eigenvalue
  - [x] Proper function comments
  - [x] Deflation a.l.a effenberger(?)
- Newton methods
  - [x] Proper function comments `augnewton`
  - [x] Proper function comments `resinv`
  - [x] Proper function comments `newton`
  - [x] Proper function comments `rfi`
  - [x] Proper function comments `quasinewton`
  - [x] Proper function comments `newtonqr`
  - [x] Proper function comments `implicitdet`
  - [x] Proper function comments `mslp` 
- Block Newton method
  - [x] Basic implementation 
  - [x] Proper function comments
- WEP
  - [x] Direct LinSolver on Schur complement
- Contour integral methods
  - Beyns version
    - [x] trapezoidal rule
    - [x] Proper function comments
    - [x] Eigenvector extraction
  - ~~SLEPc version~~
    *  ~~Basic implementation~~
    *  ~~Proper function comments~~
- Transformations 
   - [x] Effenberger deflation
- Core and types
  - [x] REP as SPMFs  
  - [x] Isolate Matlab dependence from main package (LinSolver)
  - Proper function comments for 
    - [x] compute_Mder, compute_Mlincomb, compute_MM
    - [x] compute_rf
    - [x] SPMF,PEP, REPs
    - [x] Projectable NEPs
    - [x] nep transformations
    - [x] linear system solvers
    - [x] linear eigenvalue problem solvers
    - [x] companion
- Practical
  - [x] Introduce a copyright/copying licence
  - [x] Proper first page
  - [x] A short/technical manuscript which we can put on arxiv such that it can be cited.

By proper function comments I mean:
- Function definition with optional parameters
- Description of function (reference newton() for the common parameters)
- A self-contained example.
- References

I have already done "proper function comments" for `newton()` and `resinv()`. We should do it using Markdown, i.e., the rules here https://docs.julialang.org/en/stable/manual/documentation/

Migrated from https://gitr.sys.kth.se/nep-pack/nep-pack-alpha/issues/26

**Comment by meleg** [comment]
The method iar_chebyshev is now fully functional. You are welcome to test it, report bugs and give advices for improving it. Documentation is still needed, I will add it soon.

**Comment by jarlebring** [comment]
Nice work. I like that you show how one can form a sum of two NEPs. 

I think selecting `γ` not equal to one does not work for the SPMF (and also not work for the `ComputeY0Cheb_QDEP`). I added two tests. I would suggest we try to write the derivation of the SPMF-formula in the manuscript in a clear way, before we try to include scaling.

**Comment by meleg** [comment]
@jarlebring thanks for the bug reporting! Now the method iar_chebyshev supports shift and scaling for SPMF format as well (and the test passes). Recall that this cannot be incorporated in the method itself but the problem is explicitly transformed.

However, by reading your comment it feels you want a deeper change, i.e., include the shift and scaling in the method. Is this correct? We had a discussion about that for the general case and I remember it was not easy. Do you think is simpler for the SPMF format?

About the case `ComputeY0Cheb_QDEP`, the point is that the the user-provided method `compute_y0_method` does not depend on `γ` and it is implicitly assumed `γ=1`. I can fix this function or change back `γ=1` in order to pass this test.

**Comment by jarlebring** [comment]
> change, i.e., include the shift and scaling in the method. Is this correct? We had a discussion about that for the general case and I remember it was not easy. Do you think is simpler for the SPMF format?

Yes. I don't see why the SPMF-computation formula would not be able to handle shift and scale.  As I wrote in my above, I suggest to clean up the derivation and put it into the MS.

**Comment by meleg** [comment]
I decided to remove the test for `ComputeY0Cheb_QDEP`  with shift and scale. I did it because the function `compute_y0_method` for the QDEP is a combination of the functions `compute_y0_method` for PEP and DEP. Recall that for DEP and PEP we do not have formulas for `compute_y0_method` if the shift and scale are not standard (`shift=0, scale=1`).

**Comment by eringh** [comment]
A naive eigenvector extraction in Beyn 4f32fedd3f759e1f5ff4dacc48a84d1b4a5e6c4f

**Comment by jarlebring** [comment]
Last checkbox, short manuscript describing main features: https://arxiv.org/abs/1811.09592
