### ISSUE TITLE
full matrix free

### ISSUE THREAD

**Issue by rveltz** [nep-pack/NonlinearEigenproblems.jl#263]
Hi,

Is it possible to solve $M(lambda)v=0$ where for each `lambda`, we only have access to the evaluation $v -> M(lambda)v$?

Thank you

Best

**Comment by jarlebring** [comment]
Yep. It's easy to define with `Mder_Mlincomb_NEP`
```
n=5;
AA=[5.0   3.0    4.0  -21.0    7.0
 -1.0  -4.0  -20.0  -10.0   10.0
  3.0  -2.0   -9.0    7.0  -17.0
  2.0  -6.0   -2.0   -5.0  -16.0
 -5.0   4.0  -21.0   -1.0  -18.0];
BB=[10.0    5.0    0.0  -11.0  -3.0
  3.0  -20.0   -3.0    2.0  -3.0
 15.0    1.0  -11.0   -4.0   1.0
  2.0  -20.0   16.0   -3.0  12.0
  5.0   31.0  -13.0   16.0  -2.0];
f=  (s,x) -> -s*x+AA*x+BB*x*exp(-s)
nep=Mder_Mlincomb_NEP(n,s->s,0,f);
```
Not so many solvers support so little NEP-info, but you can use broydens method if you specify an `approxnep` which can be a very bad approximation, e.g., the identity matrix. 
```
julia> approxnep=SPMF_NEP([Matrix{Float64}(I,n,n)],[s->one(s)]);
julia> (λ,v)=broyden(ComplexF64,nep,approxnep);
julia> norm(-s*x+AA*x+exp(-s)*BB*x)/norm(x)
3.7682219008410606e-15
```
That will not work so well for huge problems. If you have access to the action of M', e.g., computable with finite difference you can use some other solvers
```
function f2(s,X)
   if (size(X,2)  == 1)
        return f(s,X)
   elseif (size(X,2) == 2)
        ee=sqrt(eps());
        return f(s,X[:,1])+(f(s+ee,X[:,2])-f(s-ee,X[:,2]))/2ee;
   else
      error("Not implemented")
   end
end
nep2=Mder_Mlincomb_NEP(n,nothing,0,f2,2);
```
In general, I think it is difficult to get good performance without knowing somthing more about M, e.g., a very crude approximation (to be used as a M-approximation directly or to be used as a preconditioner in the GMRES-linsolver).
```
Mapprox=AA+BB;   # Crude approximation of M
nep3=Mder_Mlincomb_NEP(n,(s,d) -> Mapprox,1,f2,2);
quasinewton(nep3,λ=-0.6,tol=1e-10,maxit=500)
```

**Comment by rveltz** [comment]
That's for distributed delays. I can right whatever differential of M(lambda), it's just that the matrix is large and the number of different delays is large too.

**Comment by jarlebring** [comment]
With distributed delays you have access to many other things than the matrix vector product action, e.g. an approximate matrix is usually also accessible with a crude numerical integration. In the best case you can create an appropriate `SPMF_NEP`:

https://github.com/nep-pack/NonlinearEigenproblems.jl/blob/master/src/gallery_extra/distributed_example.jl

Even if you can't phrase it as a `SPMF_NEP` you can create a NEP like above using `Mder_Mlincomb_NEP`.
