### ISSUE TITLE
Support for vector-nonlinear NEPs ?

### ISSUE THREAD

**Issue by BambOoxX** [nep-pack/NonlinearEigenproblems.jl#268]
Hi all, your package looks very nice but I wonder, do you have plans to support problems with vector nonlinearity such as `M(\lambda,v)v = 0` ?

**Comment by jarlebring** [comment]
Short answer: No. What is typically called a NEPv: eigenvalue problems with eigenvector nonlinearity is defined as $A(v)v=\lambda v$ is already a quite different type of problem. When you combine NEPs and NEPvs as you suggest, one may ask what the difference is from a nonlinear system of equations. So, there are no plans to incorporate it either. Would be better suited for a different package.
