### ISSUE TITLE
Native support of nlevp-methods

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#37]
The current way of using nlevp-examples is to
1. create a  `GalleryNLEVP.NLEVP_NEP` by calling `GalleryNLEVP.nep_gallery`
2. (optional) call `GalleryNLEVP.nlevp_make_native` which creates a SPMF-object

This construction is nice since it is general, but it requires an installation of MATLAB. For some (or all) examples in NLEVP we may want to create native support in `Gallery.nep_gallery`. 

This can be done with by saving the files with our Serializer util: `src/utils/Serializer.jl`. For usage see `test/serialization.jl`.    (*Edi*t removed usage MAT)

I have already done it for "gun"-problem by adding an example  "nlevp_native_gun" in `Gallery.nep_gallery`. 

Suggested things to do:
* [x] Nativize "fiber" 
* [x] Nativize "hadeler" (convert to DEP?)
* [x] Nativize "pdde_stability" to PEP
* [ ] Nativize "railtrack"
* [x] Nativize "loaded_string" (convert to REP?) 
* [x] Nativize "cd_player" (PEP)
* [x] Make the NEP-PACK find installed NLEVP files in a general way.

**Comment by eringh** [comment]
For some of these we will need special functions implemented as matrix functions (like "fiber"). Either we do that ourselves, or we look at, e.g., https://github.com/robzan8/MatFun.jl
It seems as if it is discussed in issue 5840 of [the Julia repo](https://github.com/JuliaLang/julia/issues/)

**Comment by jarlebring** [comment]
For the "fiber" problem I would suggest that we do a more hard-coded version to start with. A "straightforward" but dirty approach would be to sample the complicated scalar function in matlab, save the sample points in a file and load it in julia.

**Comment by jarlebring** [comment]
Fiber handled in #77.

**Comment by jarlebring** [comment]
For future reference: `loaded_string` example is a problem with Toeplitz matrices and should eventually maybe use ToeplitzMatrices package. The current implementation of `loaded_string` is prepared for this.

**Comment by jarlebring** [comment]
The railtrack is t-palindromic qep. QEPs are quite easy to convert with the Julia-MATLAB-interface, so I think we don't need an "efficient" native implementation. Closing issue.
