### ISSUE TITLE
Type stability for DEPs

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#44]
At the meeting 2018-07-17 @eringh proposed to look into type stability. Rather than trying to make NEP-PACK type stable right now (which seems like a huge task) we can try it out for a part of the code, and see how difficult it is and if we get perforance improvement. I think we can first try to make the functions associated with one NEP-type type stable. I suggest the `DEP`.

The command `@code_warntype` is useful when investigating type stability. For instance, if you run it on a DEP to check type stability of the `size` command:
```
julia> nep=nep_gallery("dep0");
julia> @code_warntype(size(nep,1))
Variables:
  #self# <optimized out>
  nep::NEPTypes.DEP
  dim <optimized out>

Body:
  begin 
      return (Core.getfield)(nep::NEPTypes.DEP, :n)::Int64
  end::Int64
```
At the end you see that the output is Int64, so julia could determine the output type based on input type => type stable.

In contrast, if we run it on `issparse` we get
```
julia> @code_warntype(issparse(nep))
Variables:
  #self# <optimized out>
  nep::NEPTypes.DEP

Body:
  begin 
      return (NEPTypes.issparse)((Base.arrayref)((Core.getfield)(nep::NEPTypes.DEP, :A)::Array{#s739,N} where N where #s739<:(AbstractArray{T,2} where T), 1)::AbstractArray{T,2} where T)::Any
  end::Any
```
At the end we see `Any`, which means julia could not determine the output type based on the input types. I think we should try to make `issparse` and `compute_Mder()` type stable first (and then look at `compute_Mlincomb` and maybe some other functions). 

Type stable for DEP:
* [x]  `size()`
* [x]  `issparse()`
* [x]  `compute_Mder`
* [x]  `compute_Mlincomb`

[This julia discourse discussion](https://discourse.julialang.org/t/type-stability-and-array-of-matrices/12483/2) will probably be helpful. The size-function was made type-stable in ba09cd76278ba754211183c252b1bca3da9f0005 and 248f2278606cb464c0b6e409c3f34860a419c976.

**Comment by eringh** [comment]
This is one of the reasons why I have been bringing up the topic if we should have the NEPs as parametric types. It is complicated, and it is true that you might have a NEP that is real but with complex eigenvalues, or vice versa. Nevertheless, I suspect it might be difficult to get some type stability in, e.g., `compute_Mder` without knowing the type of the matrices in the NEP.

**Comment by jarlebring** [comment]
Related to  59ba8186d8db0e1f030cfde9eeee97c1a98e37ec. If we would define the function as
```
function compute_Mlincomb(nep::DEP,λ::T,V::Array{T,2};a=ones(T,size(V,2))) where {T<:Number}
```
I suspect we would gain type information: since by construction  `typeof(λ), eltype(V)` and `eltype(a)` would be the same, i.e. good for JIT-compiler. The downside: we would need to be more careful in the code that calls it to ensure that the types are the same.  This seems acceptable for me since we anyway have arithmetic type available in the solver-code.

**Comment by meleg** [comment]
@jarlebring I will try to fix the function according to your suggestion. However with the specialized function for compute_Mlincomb to a DEP we gain a 10x speedup!
If you time the old and the new functions we have
```
nep=nep_gallery("dep0_tridiag",10000)
n=size(nep,1);	k=60;
V=rand(n,k);	λ=rand()*im+rand();	a=rand(k)
z1=compute_Mlincomb(nep,λ,copy(V),a=a)

compute_Mlincomb(nep,λ,V,a=a)
@time z1=compute_Mlincomb(nep,λ,V,a=a)

# old way of compute_Mlincomb used for DEP
import NEPCore.compute_Mlincomb_from_MM
z2=compute_Mlincomb_from_MM(nep,λ,V,a)
@time z2=compute_Mlincomb_from_MM(nep,λ,V,a)
println("Error=",norm(z1-z2))
```
That gives 
```
  0.011026 seconds (65 allocations: 24.572 MiB, 14.29% gc time)
  0.293564 seconds (206 allocations: 67.667 MiB, 0.59% gc time)
Error=8.496149338097194e-12
```

**Comment by jarlebring** [comment]
Following up on the previous two post. The definition of DEP if it is parametric would be something like:
```
type DEP {Tp<: Number, MatType <: AbstractMatrix{Tp}} <: AbstractSPMF
 n::Int
 A::Array{MatType,1}
 tauv::Array{real(Tp),1}
end
``` 
Conceptually, we need to remember that `Tp` here defines a problem type, whereas `T` in `compute_Mlincomb` above refers to arithmetic type. For me, it is very unclear how the mixed situation should be properly handled, e.g., if we define a real DEP, but run an algorithm in complex arithmetic.

Suppose `dep` is `DEP{Float64,Matrix{Float64}}`, what should happen if we run

```
julia> V=randn(Complex128,2); s=1+1im;
julia> z=compute_Mlincomb(dep,s,V)
```
1. Throw type mismatch error? 
2. Automatically convert the dep to `DEP{Complex128,Matrix{Complex128}}`
3.  Leave it up to the solver-developer
4.  Leave it up to the `compute_Mlincomb` developer to develop "mixed type" implementations  

Similar mixed type operations occur in other places in julia, e.g., when you multiply a complex matrix with a real vector. In that case I think it is handled by the concept of promotion (smth like solution 2). Still not sure this will lead to a loss of performance in our case.

**Comment by jarlebring** [comment]
Very nice @meleg. Very concrete how the general purpose functions (e.g. SPMF-format) only leads so far in terms of performance.

**Comment by eringh** [comment]
I think promotion usually degrades performance. On the other hand, perhaps it is the best we can do in order not to make initial threshold to use the package too high.

**Comment by eringh** [comment]
As I hinted at in the above referenced comment, I think we maybe should consider also a broader term of type-stability. Technically a function could be type stable, but return non-intuitive types. In the example above `compute_Mlincomb` returned a matrix with one column, rather than a vector.

Maybe we should set up some unit tests to consider the output types of (some of) the basic operations.

**Comment by jarlebring** [comment]
I think I managed to make `compute_Mlincomb` type-stable for DEPs without using parametric types in b8cacafeec95837f0cedf8fe2b0376c5c8163802. The trick: Understand the difference between  ` z+=view(V,:,1:1)` and `z[:]+=view(V,:,1:1)`. The first option can potentially change the type (not stable), whereas the second option puts a new value in the memory where `z` is stored.

Compare these two: 
```
julia> z1=randn(3);
julia> z2=randn(3);
julia> z1+=u  % Changes type of z1
3-element Array{Complex{Float64},1}:
    -3.8753-0.591057im
   0.653142+0.278404im
 -0.0536795+0.5535im  
julia> z2[:]+=u % Throws an error instead of changing the type 
ERROR: InexactError()
Stacktrace:
 [1] convert at ./complex.jl:31 [inlined]
.... 
```

Example that `compute_Mlincomb` is type stable:
```
julia> A=randn(3,3); B=randn(3,3); dep=DEP([A,B]);
julia> s=randn(); V=randn(3,2);
julia> @code_warntype(compute_Mlincomb(dep,s,V))
Variables:
  #self#::NonlinearEigenproblems.NEPCore.#compute_Mlincomb
  nep::NonlinearEigenproblems.NEPTypes.DEP
  λ::Float64
  V::Array{Float64,2}

Body:
  begin 
      SSAValue(2) = (Base.arraysize)(V::Array{Float64,2}, 2)::Int64
      return $(Expr(:invoke, MethodInstance for #compute_Mlincomb#33(::Array{Float64,1}, ::Function, ::NonlinearEigenproblems.NEPTypes.DEP, ::Float64, ::Array{Float64,2}), :(NonlinearEigenproblems.NEPTypes.#compute_Mlincomb#33), :($(Expr(:invoke, MethodInstance for fill!(::Array{Float64,1}, ::Float64), :(Base.fill!), :($(Expr(:foreigncall, :(:jl_alloc_array_1d), Array{Float64,1}, svec(Any, Int64), Array{Float64,1}, 0, SSAValue(2), 0))), :((Base.sitofp)(Float64, 1)::Float64)))), :(#self#), :(nep), :(λ), :(V)))
  end::Array{Float64,1}
```

**Comment by jarlebring** [comment]
This is solved in PR #49. I needed to make it a parametric type in a different way than what described above.

**Comment by eringh** [comment]
This looks promising!

However, I encountered a slight problem. Not sure if it is in the miss-match between problem-type and arithmetic-type, or in the macro `@method_concretely_defined`. Consider the following code:

```
nep = nep_gallery("dep0_sparse",40);

u = ones(size(nep,1),1);
λ = 1.0;
p1 = compute_Mlincomb(nep,λ,u);

u = ones(size(nep,1));
λ = 1.0;
p2 = compute_Mlincomb(nep,λ,u);

u = ones(size(nep,1),1);
λ = 1.0+0.1im;
p3 = compute_Mlincomb(nep,λ,u);

u = ones(size(nep,1));
λ = 1.0+0.1im;
p4 = compute_Mlincomb(nep,λ,u);
```

Here only `p1` computes, all others reach the `error` on line 121 in` NEPCore.jl`. Any ideas on why?

**Comment by eringh** [comment]
Did we answer the question of what to do when the type of the problem is one and the type of the arithmetic is another?
I guess there are cases when the problem is real, but one wants to use complex arithmetic.

Should we overload the `eltype`-function for NEPs? I am not sure if it is useful. I guess it might depend on the answer to the question above.

**Comment by jarlebring** [comment]
The main intent was to make a type stable implementation for identical types (`typeof(lambda)=eltype(V))` i.e. not covering your case) although I added a couple of lines which some support some mixed type cases. This issue topic is drifting. Can you please open a new issue for discussion of operations with mixed types and promotion? Preferably with a small use-case, and concise description.
