### ISSUE TITLE
Test Coverage Reports

### ISSUE THREAD

**Issue by maxbennedich** [nep-pack/NonlinearEigenproblems.jl#45]
I've added test coverage reporting through [Coveralls](https://coveralls.io/github/nep-pack/NonlinearEigenproblems.jl?branch=master) and [Codecov](https://codecov.io/gh/nep-pack/NonlinearEigenproblems.jl). You can click the badges at the top of [README.md](https://github.com/nep-pack/NonlinearEigenproblems.jl) to see the reports, which are automatically generated on each successful build. From there, you can dig into the coverage for each file, and even see line-by-line what's covered by tests and what's not.

For files and folders that don't need to be unit tested, we can add them to the list of excluded files in [this script](https://github.com/nep-pack/NonlinearEigenproblems.jl/blob/master/test/submit_test_coverage.jl), so that they don't dilute the coverage percentage. I added a few already, but feel free to add more.

**Comment by eringh** [comment]
Great! I tried to improve coverage on NEPCore by adding some simple tests. Mostly we did not test things that errored, so now I test that they indeed throw an error. 4c86f31dfe48638ef39c10b9c057aa7cbc5b5a05
