### ISSUE TITLE
Type stability and arithmetic type

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#50]
After PR #44 simple algorithms such as `augnewton` are almost type stable if you also provide the arithmetic type. However, if you don't provide the arithmetic type (e.g. just `augnewton(nep)` instead of `augnewton(Complex128,nep)`) it is not type stable. It becomes type-stable if we add the types to the kwargs. It seems to work to instead of 
```
    function augnewton(::Type{T},
                       nep::NEP;
                       errmeasure::Function = default_errmeasure(nep::NEP),
                       tol=eps(real(T))*100,
                       maxit=30,
                       λ=zero(T),
                       v=randn(real(T),size(nep,1)),
                       c=v,
                       displaylevel=0,
                       linsolvercreator::Function=backslash_linsolvercreator,
                       armijo_factor=one(real(T)),
                       armijo_max=5) where {T<:Number}
```
do
```
   function augnewton(::Type{T},
                       nep::NEP;
                       errmeasure::Function = default_errmeasure(nep::NEP),
                       tol::Real=eps(real(T))*100,
                       maxit::Integer=30,
                       λ::Number=zero(T),
                       v::Vector=randn(real(T),size(nep,1)),
                       c::Vector=v,
                       displaylevel::Int=0,
                       linsolvercreator::Function=backslash_linsolvercreator,
                       armijo_factor::Real=one(real(T)),
                       armijo_max::Integer=5) where {T<:Number}
```
Commit for `augnewton` coming soon. 

We should add types to all kwargs in all NEP-solvers.  In general and in particular while doing this change, we can try to remember to use `Vector` or `Matrix` instead of `Array{,1}` and `Array{,2}`.

**Comment by eringh** [comment]
The way type stability is achieved by those typa annotations may be natural. But it is also a bit weird since no concrete types are specified. At the time of call, more specific type informations should be available. Also in the SIAM Rev. article they write about the type system that:
> _[...] one is never required to specify types, and neither are type annotations necessary for performance._

**Comment by jarlebring** [comment]
Julia 0.6 issue so can be closed.
