### ISSUE TITLE
Style guideline - trailing whitespace

### ISSUE THREAD

**Issue by maxbennedich** [nep-pack/NonlinearEigenproblems.jl#57]
The default behavior of Juno/Atom is to remove trailing whitespace in files on save. This can be turned off to preserve existing whitespace. Unless everyone uses the same behavior, we will end up with unnecessarily large diffs and merge conflicts. See for example [this changeset](https://github.com/nep-pack/NonlinearEigenproblems.jl/commit/f8bfc702c231161432528aeee307ac13ad5f4dee#diff-7f80e22b623daa607150cf99b5713aae). 

I have a slight preference for removing trailing whitespace, which is also the [guideline used within the Julia Language project](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#code-formatting-guidelines). Not doing this, I think that we will 1) accumulate random whitespace over time which will make editing a bit less efficient, and 2) have external contributors remove trailing whitespace in entire files and create large changesets for tiny changes, since that's the default behavior in Juno and Julia.

Opinions?

**Comment by eringh** [comment]
I think it sounds good to have a default to remove trailing white spaces. I think observations 1) and 2) are relevant.

I have that standard feature turned on in my editor.

**Comment by jarlebring** [comment]
:+1:  for "no trailing whitespace" style. I think this does the job .emacs:
```
(add-hook 'before-save-hook 'delete-trailing-whitespace)
```

**Comment by maxbennedich** [comment]
Great. I've updated our style guideline wiki page. Closing this issue.
