### ISSUE TITLE
IAR Chebyshev tests sensitive to random seed

### ISSUE THREAD

**Issue by maxbennedich** [nep-pack/NonlinearEigenproblems.jl#60]
Two IAR Chebyshev tests started failing in Julia 0.7 due to the random number generator having changed between Julia 0.6 and 0.7 ("DEP with delays>1" and "DEP format with ComputeY0ChebSPMF_NEP"). I fixed it by changing the random seed from 0 to 1 for those tests in [this commit](https://github.com/nep-pack/NonlinearEigenproblems.jl/commit/9043bde08f1776cd4e331438b34aa4da38998378). This issue is just to verify that this is expected; for example perhaps the tolerance termination criteria in those tests had been tuned to the specific values returned by `rand`?

**Comment by maxbennedich** [comment]
@meleg suggests looking at the test and change the way the tolerance is implemented (alternatively change the tolerance value), and then change the random seed back from 1 to 0.

**Comment by maxbennedich** [comment]
Great!

With this change, could we change the random seed in `Gallery.jl` (for the `dep0_tridiag` problem) from 1 back to 0? I had to change it to 1 before to make the test pass, but we mentioned that it'd be nicer to use random seed 0 where possible.

**Comment by meleg** [comment]
I think so! I still have to work on the issue #65 
I do not it the change you propose is related to that issue.
