### ISSUE TITLE
Travis failure PolynomialZeros

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#63]
Travis currently fails with this error message:
```
   Testing NonlinearEigenproblems
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package PolynomialZeros [11d3f387]:
 PolynomialZeros [11d3f387] log:
 ├─possible versions are: [0.0.1, 0.1.0] or uninstalled
 ├─restricted to versions * by NonlinearEigenproblems [67991c06], leaving only versions [0.0.1, 0.1.0]
 │ └─NonlinearEigenproblems [67991c06] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─NonlinearEigenproblems [67991c06] is fixed to version 0.1.0
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```
This started happening in a branch I was working on, but now also happens in master (after a almost empty commit). 

I don't know the reason but it might be related to this: I think Julia's new package reasoning regarding version is quite restrictive. As far as I remember, it will not automatically try to use the newest version.  So our package will not try to use a newer version of PolynomialZeros, unless we explicitly update Manifest. This is intentional for reproducability.

**Comment by jarlebring** [comment]
A temporary workaround is to remove the PolynomialZeros dependency in manifest, project and neptypes. This makes compute_rf fail but the test runs cf branch compute_types

**Comment by maxbennedich** [comment]
Hmm, I wonder if we should try to upgrade our package to Julia 1.0 right away then. Even when it worked, that package threw a lot of deprecation warnings, which I presume they have fixed in their Julia 1.0 compatible version.

It will mean that deprecations are reported as errors, without instructions on how to fix them, but that might be acceptable given the walkthrough we had yesterday, and the fact that we shouldn't have/introduce any new deprecations anyway.

**Comment by jarlebring** [comment]
Okay. Might be worth a try. If there is an unresolvable conflict on 0.7, there might be (other) unresolvable conflicts on 1.0?  Maybe we run into trouble with other packages. The easiest thing is probably just to try it out.

**Comment by jarlebring** [comment]
I was unable to install PolynomialZeros also on Julia 1.0. The same dependency problem. I think we have to treat PolynomialZeros as currently broken => The master-status where PolynomialZeros is commented out and two tests disabled seems like the reasonable temporary solution. I have filed an issue with the PolynomialZeros project.

**Comment by maxbennedich** [comment]
The package now works, and the tests pass, in Julia 1.0. I can get it to work in Julia 0.7 locally by first adding it to our project through 1.0. But that doesn't work in Travis, and would be a lot to ask for end users. We can probably get it to run in Travis through some hacking, or we can just drop support for 0.7 and move on to 1.0 (which I feel that we could do once Emil has successfully merged his JD branch).

**Comment by eringh** [comment]
I am reaching the state where we could merge my JD-branch to master. There might still be improvements to it, but at this point I start to feel ready with it. Still cleaning up some deprecations, but I synced with master yesterday evening. And by this morning it runs on 0.7.

**Comment by maxbennedich** [comment]
Great work @eringh, looks like your branch now runs without complaints in both 0.7 and 1.0!

**Comment by jarlebring** [comment]
Dropping 0.7-support would be perfectly fine with me.

**Comment by maxbennedich** [comment]
PolynomialZeros has been added back, and builds successfully in Travis (Julia 1.0 only). Closing this issue.
