### ISSUE TITLE
Improve accuracy in test performance/memory report

### ISSUE THREAD

**Issue by maxbennedich** [nep-pack/NonlinearEigenproblems.jl#67]
The performance report produced by `runtests.jl` is currently very inaccurate. This is caused by the timing including JIT compilation. Running the test twice gives very different numbers. For example, Travis reports that `beyn.jl` takes **57.3s** and uses **1.56GiB** memory. Running it twice on my system, the second run takes only **226ms** and uses **24MiB** memory. This makes the numbers reported by Travis very unreliable, since one wouldn't know if regressions/improvements are caused by differences in the JIT compilation or in the code. I think it would be useful to have a way to somewhat accurately measure the performance of our code itself.

I don't think we need ~millisecond precision at this point (since that would mean taking many measurements which would take a long time), but just running each test twice and taking the second timing might be enough.

It would also be interesting to look into measuring and reporting performance on individual `@testset` blocks for more granularity.

**Comment by maxbennedich** [comment]
Running each test twice on Travis, performance reported is much more accurate, but the tradeoff is that the elapsed time to run the test suite (and hence complete the build) went from ~11 minutes to ~16 minutes.

**Comment by jarlebring** [comment]
Are you sure we want to do these type of timings on travis? Since it's on a cloud it is anyway difficult to say something conclusive. 

Another option would be a script which we have to run somewhere else, e.g., manually locally (or another repo). That way the comparison can be more extensive, e.g. by using running a BenchmarkTools-run on every script in the test-directory. Every run could be saved in a structured way with commit hash, timing information and computer information. I'm not sure where this should be saved - maybe a different repository in the NEP-PACK git organization.

**Comment by jarlebring** [comment]
Also, the current tests are not really built to measure performance, e.g., the waveguide tests are  intentionally small problems although it is much more interesting to measure performance on larger matrices.

**Comment by maxbennedich** [comment]
Hmm, I'm not sure what's the best way to do it. I agree it would be better to run a much more detailed benchmark in a controlled environment, but I'm not sure how to do that in practice. Are there resources at KTH we can use?

My intention with the Travis measurements was not so much to do accurate benchmarks of our algorithms, but a way to catch bugs or mistakes, such as a developer introducing an improperly supported adjoint matrix, that suddenly causes an implementation to use a lot more CPU/memory. As a developer, I think it's good to be notified about these issues as soon as possible, and as a reviewer I think it's useful to have this information readily available without having to do any additional manual steps. (While the time reported on Travis is not 100% reliable, I think the memory should be pretty accurate.)

That said, a 16 minute build is far from ideal and risks limiting our iteration speed. And that will only get longer as we add more tests.

**Comment by jarlebring** [comment]
I can't think of a clean way of connecting with computers/resources at KTH. The kerberos file-system has a quite short time-out and ssh-key exchange is blocked so it is difficult to setup something which communicates with the outside world with cron or similar. I think sysadmin don't want it for security reasons. The public version of Travis CI is used for education at KTH, no internal installations that I'm aware of. 

How about creating another repo which also runs tests on travis, but longer tests?  It might be difficult to make fully automatic, but otherwise at least we can safely keep light versions of the test in this repo.

**Comment by maxbennedich** [comment]
Yes that might be a good idea! I've been reading up a bit on Travis, and a variant of that suggestion would be to use a single repo, but different Travis jobs using their ["build matrix" feature](https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines). It could look something like this in `.travis.yml`:
```
env:
  - TEST_SUITE=units
  - TEST_SUITE=benchmark
```
And then in `runtests.jl` we could do:
```
test_suite = get(ENV, "TEST_SUITE", "units")
```

**Comment by maxbennedich** [comment]
This is what it could look like (from [this branch](https://github.com/nep-pack/NonlinearEigenproblems.jl/compare/run-multiple-travis-jobs)). So the unit tests would finish "quickly", and the benchmark / increased accuracy tests would go for a bit longer:

![image](https://user-images.githubusercontent.com/1812661/45207747-253fc500-b289-11e8-92b7-a5e9d554d988.png)

**Comment by jarlebring** [comment]
That setup sounds very nice. Is your thought that benchmark-test runs the tests twice? Or something more sophisticated?

**Comment by maxbennedich** [comment]
I think it could be nice to do a mini-benchmark (at least two runs) of each @testset, to get a bit more detailed results. But it would be great if there was a way to do this without having to complicate the way we're writing tests (ideally not modify them at all). I'll look into it a bit to see if I can come up with something.

I'll merge the build matrix branch for now since it's an improvement of what's currently in master.

**Comment by maxbennedich** [comment]
I did an experiment with timing individual `@testset`s. See [diff here](https://github.com/nep-pack/NonlinearEigenproblems.jl/compare/more-accurate-test-performance-reports) and [resulting build output here](https://travis-ci.org/nep-pack/NonlinearEigenproblems.jl/jobs/426126367#L2751).

The way it works is that a `@testset` can be prefixed by `@bench` which, with a specific environment variable set, will run a mini-benchmark on the code within the `@testset` block (currently just running the code twice), and store the results for later reporting.

With the requirements that this should run on Travis, and not require a major rewrite of our tests (splitting them into testing functionality vs performance), this was the best solution I could think of.

The alternative is to keep it simple, and just run each test script twice, like we do in `master` now. The advantage of this change is that we get much more detailed and accurate performance stats, with little additional code. (Would have been very useful during the 0.7 upgrade.) The disadvantage is that it adds some complication, and it nevertheless requires additional code; forgetting to use the `@bench` macro will exclude the test from the report. (That could however be detected by a separate unit test, which ensures that each unit test has a `@bench` statement.)

**Comment by maxbennedich** [comment]
I merged the changed discussed above. If we find it useful, there are several improvements we can make, such as automatic regression detection. I'll close this issue, and we can deal with any future improvements in separate issues.
