### ISSUE TITLE
Profiling and improving the existing methods and functions

### ISSUE THREAD

**Issue by meleg** [nep-pack/NonlinearEigenproblems.jl#68]
I am convinced that many functions are not optimized. Let us keep the track of these functions and refer to this issue when we improve them.

- [x] compute Mlincomb for DEP
- [x] compute Mlincomb for SPMF
- [x] compute Mlincomb for PEP (should be like for SPMF)

**Comment by meleg** [comment]
In my last commits (mainly in) 2cc7780a7a8d5f6e48c3e5e0cc696272620eaaf6 I have changed compute_Mlincomb for SPMF in the following way: We know that it exist a matrix S such that the following equality is fulfilled
compute_Mlincomb(λ,V,a)=a_1*MM(V,S)e_1
This is actually the function compute_Mlincomb_from_MM 
We can expand theright-hand side and we get
compute_Mlincomb(λ,V,a)=a_1*MM(V,S)e_1=a_1 A_1 V (f_1(S) e_1) + ... + a_m A_m V (f_m(S) e_1)
If we use this formula (without computing MM(V,S)) we have a huge gain.
In particular for a random SPMF of size 100000 with various kind on non-linearities and for V with 50 columns, with the new implementation of compute_Mlincomb we have
`0.076495 seconds (655 allocations: 22.673 MiB, 5.22% gc time)`
with the old implementation instead
`1.499190 seconds (687 allocations: 996.945 MiB, 21.86% gc time)`

**Comment by jarlebring** [comment]
Good point. I think your observation that it is compute_Mlincomb(SPMF is inefficient can also be explained by the fact that compute_MM(SPMF is not efficient. I think compute_MM(SPMF needs a complete rewrite now that we know more about type stability and parametric types. It may change your conclusion a bit. Let me put an issue on that.

**Comment by meleg** [comment]
I think that compute_MM is in general slow independently on the implementation. The two formulas have different complexities. I have even tested this in matlab.

The idea behind this change is simply to move parenthesis, i.e., it is faster to compute A*(B*x) then computing (A*B)*x

**Comment by jarlebring** [comment]
Ah. Good point. compute_MM always returns a matrix (and does not support matrix vector products). So different issues indeed.
