### ISSUE TITLE
Rewrite of compute_MM(SPMF 

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#70]
As pointed out in #68, `compute_MM(::SPMF` is not efficient. The type of "optimization" we did for `compute_MM(::DEP` also needs to be done with a general SPMF. Similar to the DEP we need to make SPMF parametric with respect to `AbstractMatrix`. Here, I think we also need to make it parametric with respect to the internal type of the functions provided. Otherwise we can never have type stability, since the compiler would not be able to determine the output type of `fi(S)`. 

So, the SPMF would be something like this:
```
    struct SPMF_NEP{Ftype<:Number,  T<:AbstractMatrix} <: AbstractSPMF
         n::Int
         A::Vector{T}   # Array of Array of matrices
         fi::Vector{Function}  # Array of functions
.... 
```
The type logic of the function is that the functions `f(S)` should always return a matrix with greatest type of `Ftype` and `eltype(S)`. 

**updated**
Rewrite includes:
* [x] Make compute_Mlincomb type stable 
* [x] Independent implementantion on compute_Mder  (not relying on compute_Mder_from_MM)
* [x] Make compute_Mder type stable 
* [x] Make compute_MM type stable
* [x] Make SPMF parametric
* [ ] Reporting that it gets better

**Comment by eringh** [comment]
Sounds like a good idea if we want type stability. Question is if the JIT compiler would be able to see the return statements and compile for it.
Maybe something like [this](https://docs.julialang.org/en/latest/manual/performance-tips/#Annotate-values-taken-from-untyped-locations-1) could be used by the method developers.
Or maybe take a look into something like [this](https://github.com/yuyichao/FunctionWrappers.jl).

**Comment by maxbennedich** [comment]
Agreed, sounds like a good idea! Getting everything type stable sounds a bit tricky if the calculation needs to promote type depending on input, but maybe achievable. Do we need to support different types within the vectors of matrices or functions? For example that one matrix or function could be complex, and another not?

`FunctionWrappers` looks very interesting, it's exactly what I've been missing in Julia! Would be interesting to see if we can apply it in any of our code to get better type stability.

**Comment by jarlebring** [comment]
FunctionWrappers would have to be carefully looked in particular wrt maturity.

>  Getting everything type stable sounds a bit tricky if the calculation needs to promote type depending on input, but maybe achievable

I'm in favor of enforcing that all basic Number-types (in all combinations in inputs) should be supported for our core NEP-types (systematically tested for many compute functions since #62). If we do correct type NEPType-parameterization, I'm pretty sure we can determine the type from the types of the inputs. This is already achieved for the `DEP`. 

> Do we need to support different types within the vectors of matrices or functions? For example that one matrix or function could be complex, and another not?

For our basic NEPtypes, I would say yes, we should support it.

**Comment by jarlebring** [comment]
Fixed in PR.
