### ISSUE TITLE
Support for changing number of UMFPACK iterative refinements

### ISSUE THREAD

**Issue by maxbennedich** [nep-pack/NonlinearEigenproblems.jl#72]
The number of iterative refinements in UMFPACK defaults to 2. By lowering this value, it is possible to greatly speed up the solver. For many applications, one iterative refinement might be enough (for the example below, the second refinement is not needed), while zero iterative refinements might compromise too much accuracy. Changing this value could speed up methods that rely heavily on system solves (such as NLEIGS). We could perhaps make this configurable in `DefaultLinSolver`.

```julia
julia> using SuiteSparse, LinearAlgebra, BenchmarkTools

julia> n = 10000;

julia> A = I + sprandn(n, n, 0.0005);

julia> y = randn(n);

julia> luf = lu(A);

julia> @btime global x = luf \ y; norm(A*x - y)
  52.467 ms (7 allocations: 625.20 KiB)
1.2050980166311244e-12

julia> SuiteSparse.UMFPACK.umf_ctrl[8] = 1;

julia> @btime global x = luf \ y; norm(A*x - y)
  34.722 ms (7 allocations: 625.20 KiB)
1.2050980166311244e-12

julia> SuiteSparse.UMFPACK.umf_ctrl[8] = 0;

julia> @btime global x = luf \ y; norm(A*x - y)
  15.467 ms (7 allocations: 312.70 KiB)
4.9111032477641746e-9
```

**Comment by jarlebring** [comment]
Sounds good. I would propose to extend the `DefaultLinSolver`-struct to have an `umfpack_refinement::Int`, which can be taken as a parameter in the constructor so we get
```
    function DefaultLinSolver(nep::NEP,λ,umfpack_refinement)
``` 
and as an optional parameter in `default_linsolvecreator`:
```
    function default_linsolvercreator(nep::NEP, λ;umfpack_refinement=2)
```
That way, it can be used in a call to the NEP-solver still in a one-liner:
```
  iar(nep;linsolvecreator=(nep,λ) ->default_linsolvercreator(nep,λ,umfpack_refinement=1) 
```

**Comment by eringh** [comment]
Seems as a nice thing to be able to configure.

**Comment by maxbennedich** [comment]
Should we support iterative refinements for non-sparse matrices too? Or is that not a use case that will occur in practice? In the NLEIGS code, this is currently supported; see the "improve accuracy" step in the `solve` method in `lusolver.jl`, or the following example:
```julia
julia> n = 5000; A = randn(n,n); y = randn(n); F = factorize(A); x = F\y; norm(A*x-y)
2.475838420420249e-9

julia> res = y-A*x; err = F\res; x += err; norm(A*x-y)
2.8065630044424448e-12
```
Compare with sparse (where this is handled by UMFPACK):
```julia
julia> A = randn(n,n); y = randn(n); F = factorize(sparse(A)); x = F\y; norm(A*x-y)
6.181201353773444e-12
```

**Comment by maxbennedich** [comment]
After discussion with Elias, we decided to not support iterative refinements for non-sparse matrices at the moment.
