### ISSUE TITLE
Use LinSolvers in NLEIGS

### ISSUE THREAD

**Issue by maxbennedich** [nep-pack/NonlinearEigenproblems.jl#79]
Use LinSolvers in NLEIGS, similar to how it's done for other methods. The LU cache would then cache `LinSolver` objects.

**Comment by jarlebring** [comment]
:+1: That way we can use other linear system solvers in NLEIGS.

**Comment by maxbennedich** [comment]
Done, see PR #87. I left the LinSolver cache in the NLEIGS directory for now, but it is quite generic so in case it can be used in other solvers we could opt to move it out (maybe into LinSolvers).
