### ISSUE TITLE
Ritz-vector restarting for nlar

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#83]
Although there are fancy ways of restarting nonlinear arnoldi (e.g. https://link.springer.com/article/10.1007/s00211-016-0804-3), I think we should first support the simple variants of restarting. The simplest idea is just to at specified iterations compressing the basis matrix, e.g., by taking the converged eigenvectors together with a number of columns corresponding to the first ritz vectors (from the projected problem) as a new basis. Something like:
``` 

        ...
        if (mod(k,restart) == restart-1)
          Z=zeros(T,n,m+nof_restart_ritz_vecs);
          Z[:,1:m]=X[:,1:m]; # First columns correspond to eigenvectors
          Z[:,m+1:end]=Vk*yv[:,1:nof_restart_ritz_vecs]
          Q,R=qr(Z); 
          V[:,m+nof_restart_ritz_vecs]=Matrix(Q);   # Compute a thin QR-factorization of Z
          Vk=view(V,:,1:(m+nof_restart_ritz_vecs));
       end 
```
When we implement restart: The code also needs to separate between iteration count `k` and the size of the subspace `size(Vk,2)`.

(I will assign this to @upadpup directly, since he has worked on nlar the most.)

**Comment by upadpup** [comment]
I am guessing you mean we know apriori that the number of columns in Vk should be equal to maximum_subspace? Also, I am thinking we should pre-allocate Z as:
`Z =  zeros(T,n,nev+nof_restart_ritz_vecs)` 
where nev is the number of eigenpairs we want to compute, instead of allocating memory for Z each time we restart. Shouldn't that be more efficient?

**Comment by upadpup** [comment]
There is now an implementation of this version of restarted nlar in  the branch: restart_nlar. For the gun problem, the non-restarted method can't find more than 8 eigenvalues(gets stuck in loops that approach the 9th eigenvalue once in a while but never really converge) even with 500 iterations(which is maxit). With the restarted version with max_subspace=50, we get convergence to 10 eigenvalues in 180 iterations. I will now profile the two versions for information about memory allocations.

**Comment by jarlebring** [comment]
Nice. When you are ready, maybe you can put these changes in a PR. It makes it easy to comment on the code.

**Comment by jarlebring** [comment]
Is there anything else you want to do in this issue @upadpup? Otherwise it can be closed.

**Comment by upadpup** [comment]
I was thinking about overloading a single eigenvalue sorter function for
different types(like inner_solve()) instead of the current way of writing
different functions. Should be done soon.

**Comment by upadpup** [comment]
But I guess that is not specific for restarting, so I will close it now.
