### ISSUE TITLE
Use logging framework in tests

### ISSUE THREAD

**Issue by maxbennedich** [nep-pack/NonlinearEigenproblems.jl#85]
We have a large number of `print` statements in our unit tests. I think it could be a good idea to use Julia's [logging framework](https://docs.julialang.org/en/v1/stdlib/Logging/) instead. This has several advantages, such as multiple levels of logging (`@debug` and `@info`), and the ability to customize, redirect, and turn off logging. Turning off logging would be particularly useful when running tests repeatedly (which we do when we run our tests in benchmark mode).

Using the logging framework is as easy as turning `print` statements into `@info`, as in [this commit](https://github.com/nep-pack/NonlinearEigenproblems.jl/commit/ae568d2923c87ead8af01b235658b091591b392b). The default behavior is to log these statements (prepended with "Info:") on a single line, similar to the behavior of `print`.

To turn logging off, one would use this command (takes effect globally):
```
using Logging
Base.CoreLogging.disable_logging(Logging.Info)
```

To enable debug logging, one could use this:
```
using Logging
Base.CoreLogging.global_logger(Logging.ConsoleLogger(stderr, Logging.Debug))
```

One can easily create custom loggers, for example to exactly replicate the behavior of `print`. It is also possible to create custom log levels.

I am initially seeing this as a way to customize the output of our unit tests, but for future work we could also look into using this for our main code.

**Comment by meleg** [comment]
Totally agree! We should by default suppress all the prints (some of them should be re-written as well).

**Comment by maxbennedich** [comment]
In case we need this in the future... Removing "Info: " prefix can be done by:
```
Base.CoreLogging.global_logger(Logging.ConsoleLogger(stderr, Logging.Info;
    meta_formatter=(_...) -> (0, "", "")))
```
Custom logger replicating `print`:
```
struct PrintLogger <: AbstractLogger; end

import Base.CoreLogging.min_enabled_level, Base.CoreLogging.shouldlog, Base.CoreLogging.handle_message

min_enabled_level(::PrintLogger) = Logging.Info
shouldlog(::PrintLogger, args...) = true
handle_message(::PrintLogger, level, message, args...; kwargs...) = println(message)

Base.CoreLogging.global_logger(PrintLogger())
```

**Comment by jarlebring** [comment]
Sounds okay. 

In some cases we would need to use `@logmsg level message`, e.g., the inner loop in broyden displays only if displaylevel>1 wheras outer loop prints of displaylevel>0. 

Most of the changes seem to be achievable with search and replace on  `@ifd(println` ?

**Comment by maxbennedich** [comment]
Yes, I guess we could achieve that by either using a combination of `@info` + `@debug`, or perhaps better by defining new log levels altogether.

But I thought I'd start with just applying this to the output of the unit tests themselves (not the methods), since that should be very easy, and the logging in the methods can be controlled already via the `displaylevel` setting. And then in a second step we could look into if we want to use the logging framework for the methods too, instead of the `@ifd` construct.

I'll take a stab at fixing the tests in PR #86.
