### ISSUE TITLE
master broken: no method matching SPMF_NEP( ...

### ISSUE THREAD

**Issue by maxbennedich** [nep-pack/NonlinearEigenproblems.jl#90]
I'm seeing this in several tests:

```
no method matching SPMF_NEP(::Array{SparseMatrixCSC{Float64,Int64},1}, ::Array{Function,1}, ::Bool)
```

Seems to have been introduced in [this commit](https://github.com/nep-pack/NonlinearEigenproblems.jl/commit/551e100d90523798c8347ae6069eaf1470f51b53).

**Comment by meleg** [comment]
I will fix this in about 1h. Sorry about that, the tests passed on my computer I did probably something stupid before pushing.
