### ISSUE TITLE
Make LinSolvers type stable 

### ISSUE THREAD

**Issue by jarlebring** [nep-pack/NonlinearEigenproblems.jl#95]
At the meeting 2018-09-19, we said we wanted to make LinSolvers type stable. I have not been able to generate an example where it DefaultLinSolver or BackslashLinSolver fail `@code_warntype`.

**Comment by jarlebring** [comment]
Ping @eringh

**Comment by eringh** [comment]
That is great!
Maybe I was a bit unclear in my thoughts, sorry for that. I would argue that is as it should, since both of them are completely specified by their respective parametric types, and contain no un-typed or abstractly typed fields (as described [here](https://docs.julialang.org/en/latest/manual/performance-tips/#Avoid-fields-with-abstract-type-1).

However, I think that `BackslashLinSolver` can be reformulated as:
```
    struct BackslashLinSolver{T_mat<:AbstractMatrix} <: LinSolver
        A::T_mat
    end
```
i.e., there is no need for having the `T_num<:Number` parameterizing it (if my understanding for the language is better compared to when I introduced it). The `DefaultLinSolver` got a tidy-up in #84, which I think was great.

Perhaps we need to look more closely on the `GMRESLinSolver`. I can take that at a later stage. The `EigSolver` should also get a similar fix I think.

**Comment by jarlebring** [comment]
Okay. Sounds like lower priority. I expect the efficiency gain for methods using EigSolver to be quite small since it is so expensive computationally to solve eigenvalue problems.

**Comment by eringh** [comment]
f9e193a41de90ff7da9113db19c74d88902f519f

**Comment by eringh** [comment]
Why are some linsolvers/eigsolvers `struct` and some `mutable struct`?
I don't think we will update the parameters of the solvers after creation, or will we?

**Comment by eringh** [comment]
I do not manage to get type-stability for the `NativeEigSSolver`. However, the code 
```
        if(nev == 1)
            return D[1],V[:,1]
        end
```
breaks the type-stability for the `NativeEigSolver`. Do we want to keep it anyway?

**Comment by maxbennedich** [comment]
> Why are some linsolvers/eigsolvers `struct` and some `mutable struct`?
> I don't think we will update the parameters of the solvers after creation, or will we?

I generally prefer immutability (`struct`). Even if parameters are changed after creation, an option would be to create a new instance. Of course there are exceptions, but I think it's good practice to make types immutable by default.

**Comment by maxbennedich** [comment]
> However, the code [...] breaks the type-stability for the `NativeEigSolver`. Do we want to keep it anyway?

Could those be returned as (vector, matrix), to match the return type of the other code path?

**Comment by eringh** [comment]
I agree with @maxbennedich last two statements. Does @jarlebring have any other input?
I think that the format of scalar-vector was because it makes the code slightly more user-friendly. But perhaps it is not worth it.

**Comment by jarlebring** [comment]
> Why are some linsolvers/eigsolvers struct and some mutable struct?

I think this is an artefact from when we moved from julia 0.6->0.7 before we knew about the value of immutable. The mutable structs have sloppy constructors which first create and then modify. They can be easily changed to create directly with object without modifying. If we at some point in the code modify the LinSolver-objects, I think we should look carefully at those points to see if it is really necessary.

> However, the code [...] breaks the type-stability for the NativeEigSolver. Do we want to keep it anyway?

I think the problem is we have nowhere (in the documentation) clearly specified the return type of `eig_solve`. This is probably also from before we knew how to work with type stability. I would say it always returns a pair `(Vector,Matrix)`. If we enforce this, some NEP-solvers probably also needs modification.  

Note that not even `eigs` is type stable, so there are limitations to what we can achieve.
